Sprint_1
Greenteyn/messenger.practicum pull request #1
Opened 2024-12-23 13:46 UTC by Greenteyn

2024-12-23 14:29 UTC, Greenteyn commented
Обновил версию ноды в файле с тестами, потому что, Vite не работает с 16 версией

2024-12-23 20:24 UTC, aromanovnik requested changes
Добрый день, Евгений!

Работа выполнена очень хорошо: проект успешно запускается по команде `npm run start`, версия Node.js указана в проекте. Структура файлов хорошо организована. Код чистый, структурированный и читаемый. Отличная работа!

Тем не менее, есть несколько замечаний, которые потребуют доработки. Более подробно о них написано в комментариях к коду.

**Что нужно исправить**:
* Проект не настроен на Netlify. По заданию требуется, чтобы приложение было развернуто на Netlify и было доступно по ссылке для проверки.
* Согласно чеклисту, меню навигации должно быть обернуто в тег `<nav>`. Это обеспечит правильную семантику HTML, улучшит доступность сайта для пользователей и корректную работу вспомогательных технологий, таких как экранные читалки.
* По правилам семантической разметки, на всех страницах весь основной контент следует помещать в тег `main`. Это улучшает доступность и структурированность страницы, так как помогает браузерам и скринридерам правильно интерпретировать и навигировать по содержимому.
* Незакрытый тег `<span>` может нарушить структуру HTML, что приведет к некорректному отображению элементов на странице или ошибкам в браузере. Закрытие тегов важно для правильного парсинга HTML и обеспечения совместимости с различными браузерами.
* Важно, чтобы значения атрибута `name` у разных input-ов в одной форме были уникальными. Использование одинакового значения `name` для разных полей может привести к неправильной передаче данных на сервер, где будет сложно различать значения этих полей, а также к сбоям в валидации, если она полагается на атрибут `name`. Это также может вызвать некорректное поведение браузера, например, при автозаполнении или управлении формой через JavaScript. Уникальные значения name для каждого поля позволяют избежать подобных ошибок и упрощают обработку данных формы.
* В соответствии с пунктом 7 чеклиста, заголовки на странице должны быть обёрнуты в теги уровней `<h1>…<h6>` согласно их смысловой важности. Это обеспечит правильную иерархию и положительно скажется на SEO. 
* По заданию 1-го спринта каждому инпуту в формах проекта необходимо задать конкретный атрибут `name`, соответствующий требованиям. Это позволит избежать изменений в 3-м спринте при подключении к API. Сейчас поля для изменения аватара и изменения пароля не соответствуют требованиям.

**Что можно улучшить**:
* Переменную `port` лучше вынести в константу, например: `const { PORT = 3000 } = process.env`, чтобы упростить настройку для разных окружений и избежать хардкодинга.
* Поскольку интерфейс проекта русскоязычный, рекомендуется установить атрибут языка в корневом теге `<html lang="ru">`. Это предотвратит ситуации, когда устройства или браузеры могут неправильно определять язык страницы, предлагать перевод, либо автоматически изменять содержимое. Подробнее об одной из таких проблем: https://habr.com/ru/post/650907/
* Тег `script` с атрибутом `type="module"` лучше размещать внутри `head`, потому что модули загружаются асинхронно и не блокируют загрузку контента страницы.
* Закомментированный код лучше не оставлять в проекте, так как вся история изменений сохраняется в Git. В любой момент можно вернуться к предыдущим версиям и посмотреть старый код. Оставление закомментированных участков засоряет кодовую базу и снижает её читаемость.
* Все цвета лучше вынести в CSS-переменные, чтобы улучшить поддержку кода. Это позволяет мгновенно понять назначение цвета, избежать дублирования, а также облегчить изменения — достаточно подкорректировать цвет в одном месте, что повышает гибкость и масштабируемость стилей.
* Каждой картинке (тегу `img`) следует добавить информативный атрибут `alt` (Не пустой). Это важно не только для улучшения доступности сайта, но и для SEO. В случае ошибки загрузки изображения, в alt будет отображаться описание, и пользователи смогут понять, что изображение не удалось загрузить. Атрибут `alt` также необходим для пользователей с нарушениями зрения, так как специальные программы для чтения с экрана могут озвучивать текст в alt. Для дополнительной информации можно ознакомиться: https://habr.com/ru/articles/341810/
* Рекомендуется всегда указывать размеры изображений через атрибуты `width` и `height` или в CSS. Это позволяет браузеру заранее резервировать место под изображения, что предотвращает сдвиги контента и излишние перерендеры страницы, улучшая производительность и пользовательский опыт. https://habr.com/ru/companies/ruvds/articles/497876/
* Использование семантической разметки, такой как `<header>`, `<article>`, `<section>`, `<footer>`, помогает сделать сайт более доступным для пользователей с ограниченными возможностями и улучшить его ранжирование в поисковых системах. Это обеспечивает лучшую структуру и понятность содержимого для браузеров и поисковых роботов. Подробнее: https://htmlacademy.ru/blog/html/semantics


Напоминаю, что работа может быть принята только после исправления всех критических замечаний **Надо исправить**.

Удачного рефакторинга кода.

2024-12-23 20:24 UTC, aromanovnik commented on README.md
> +[Сайт на Netlify](https://greenteyn-messenger.netlify.app)
**Надо исправить**: Проект не настроен на Netlify. По заданию требуется, чтобы приложение было развернуто на Netlify и было доступно по ссылке для проверки.

<img width="732" alt="Снимок экрана 2024-12-23 в 22 38 47" src="https://github.com/user-attachments/assets/3e97867a-2600-4daf-b44d-e0eb5a2bcd61" />

2024-12-23 20:24 UTC, aromanovnik commented on vite.config.js
> +    port: 3000,
**Можно лучше**: Переменную `port` лучше вынести в константу, например: `const { PORT = 3000 } = process.env`, чтобы упростить настройку для разных окружений и избежать хардкодинга.

2024-12-23 20:24 UTC, aromanovnik commented on index.html
> +<html lang="en">
**Можно лучше**: Поскольку интерфейс проекта русскоязычный, рекомендуется установить атрибут языка в корневом теге `<html lang="ru">`. Это предотвратит ситуации, когда устройства или браузеры могут неправильно определять язык страницы, предлагать перевод, либо автоматически изменять содержимое. Подробнее об одной из таких проблем: https://habr.com/ru/post/650907/

2024-12-23 20:24 UTC, aromanovnik commented on index.html
> +    <a href="/">Главная</a> -
**Надо исправить**: Согласно чеклисту, меню навигации должно быть обернуто в тег `<nav>`. Это обеспечит правильную семантику HTML, улучшит доступность сайта для пользователей и корректную работу вспомогательных технологий, таких как экранные читалки.

2024-12-23 20:24 UTC, aromanovnik commented on index.html
> +  <script type="module" src="./src/scripts/main.js"></script>
**Можно лучше**: Тег `script` с атрибутом `type="module"` лучше размещать внутри `head`, потому что модули загружаются асинхронно и не блокируют загрузку контента страницы.

2024-12-23 20:24 UTC, aromanovnik commented on src/modules/ChatAddDeleteUserModal/index.html
> +<!-- <div class="delete-user-modal">
**Можно лучше**: Закомментированный код лучше не оставлять в проекте, так как вся история изменений сохраняется в Git. В любой момент можно вернуться к предыдущим версиям и посмотреть старый код. Оставление закомментированных участков засоряет кодовую базу и снижает её читаемость.

2024-12-23 20:24 UTC, aromanovnik commented on src/modules/ChatAddDeleteUserModal/style.css
> +  box-shadow: 0px 0px 6px 0px #00000024;
**Можно лучше**: Все цвета лучше вынести в CSS-переменные, чтобы улучшить поддержку кода. Это позволяет мгновенно понять назначение цвета, избежать дублирования, а также облегчить изменения — достаточно подкорректировать цвет в одном месте, что повышает гибкость и масштабируемость стилей.

2024-12-23 20:24 UTC, aromanovnik commented on src/pages/login/index.html
> +<title>Вход в аккаунт</title>
**Надо исправить**: По правилам семантической разметки, на всех страницах весь основной контент следует помещать в тег `main`. Это улучшает доступность и структурированность страницы, так как помогает браузерам и скринридерам правильно интерпретировать и навигировать по содержимому.

2024-12-23 20:24 UTC, aromanovnik commented on src/pages/login/index.html
> +      <span><input type="email" class="input-underline" name="email" placeholder="pochta@yandex.ru" required /></label>
**Надо исправить**: Незакрытый тег `<span>` может нарушить структуру HTML, что приведет к некорректному отображению элементов на странице или ошибкам в браузере. Закрытие тегов важно для правильного парсинга HTML и обеспечения совместимости с различными браузерами.

2024-12-23 20:24 UTC, aromanovnik commented on src/pages/registration/index.html
> +      <input type="password" class="input-underline" name="password" required /><span class="error-message">Пароли не
**Надо исправить**: Важно, чтобы значения атрибута `name` у разных input-ов в одной форме были уникальными. Использование одинакового значения `name` для разных полей может привести к неправильной передаче данных на сервер, где будет сложно различать значения этих полей, а также к сбоям в валидации, если она полагается на атрибут `name`. Это также может вызвать некорректное поведение браузера, например, при автозаполнении или управлении формой через JavaScript. Уникальные значения name для каждого поля позволяют избежать подобных ошибок и упрощают обработку данных формы.

2024-12-23 20:24 UTC, aromanovnik commented on src/pages/error/index.html
> +    <span class="error-code">404</span>
**Надо исправить**: В соответствии с пунктом 7 чеклиста, заголовки на странице должны быть обёрнуты в теги уровней `<h1>…<h6>` согласно их смысловой важности. Это обеспечит правильную иерархию и положительно скажется на SEO.

2024-12-23 20:24 UTC, aromanovnik commented on src/modules/ChatMessage/index.html
> +<div class="participant-message-block incoming-message" user-id="1"><img class="image-message"
**Можно лучше**: Каждой картинке (тегу `img`) следует добавить информативный атрибут `alt` (Не пустой). Это важно не только для улучшения доступности сайта, но и для SEO. В случае ошибки загрузки изображения, в alt будет отображаться описание, и пользователи смогут понять, что изображение не удалось загрузить. Атрибут `alt` также необходим для пользователей с нарушениями зрения, так как специальные программы для чтения с экрана могут озвучивать текст в alt. Для дополнительной информации можно ознакомиться: https://habr.com/ru/articles/341810/

2024-12-23 20:24 UTC, aromanovnik commented on src/modules/ChatMessage/index.html
> +<div class="participant-message-block incoming-message" user-id="1"><img class="image-message"
**Можно лучше**: Рекомендуется всегда указывать размеры изображений через атрибуты `width` и `height` или в CSS. Это позволяет браузеру заранее резервировать место под изображения, что предотвращает сдвиги контента и излишние перерендеры страницы, улучшая производительность и пользовательский опыт. https://habr.com/ru/companies/ruvds/articles/497876/

2024-12-23 20:24 UTC, aromanovnik commented on src/pages/chat/index.html
> +    <div class="chat-header">
**Можно лучше**: Использование семантической разметки, такой как `<header>`, `<article>`, `<section>`, `<footer>`, помогает сделать сайт более доступным для пользователей с ограниченными возможностями и улучшить его ранжирование в поисковых системах. Это обеспечивает лучшую структуру и понятность содержимого для браузеров и поисковых роботов. Подробнее: https://htmlacademy.ru/blog/html/semantics

2024-12-23 20:24 UTC, aromanovnik commented on src/modules/ProfileUserDataAvatarEditPopup/index.html
> +    <label class="">Выберите файл на компьютере<input type="file" accept=".jpg, .png"></label>
**Надо исправить**: По заданию 1-го спринта каждому инпуту в формах проекта необходимо задать конкретный атрибут `name`, соответствующий требованиям. Это позволит избежать изменений в 3-м спринте при подключении к API. Сейчас поля для изменения аватара и изменения пароля не соответствуют требованиям.

<img width="618" alt="Снимок экрана 2024-12-23 в 23 17 18" src="https://github.com/user-attachments/assets/0ee241f9-29a4-46b2-a5f4-54144b75b94b" />

2024-12-26 14:55 UTC, Greenteyn commented on src/modules/ChatMessage/index.html
> +<div class="participant-message-block incoming-message" user-id="1"><img class="image-message"
Добавил в css ширину изображения в формате `width: inherit;`, потому что, оно должно быть такой же ширины, как и блок с сообщениями. Надеюсь, это корректно

2024-12-26 14:56 UTC, Greenteyn commented on src/pages/error/index.html
> +    <span class="error-code">404</span>
Добавил стили для разных заголовков и поменял немного блоки с заголовками в проекте

2024-12-26 14:57 UTC, Greenteyn commented on src/modules/ChatAddDeleteUserModal/style.css
> +  box-shadow: 0px 0px 6px 0px #00000024;
Вроде бы, почти все вынес в переменные, где они повторяются

2024-12-26 14:58 UTC, Greenteyn commented on src/modules/ChatAddDeleteUserModal/index.html
> +<!-- <div class="delete-user-modal">
Закоментированный код удалил. Изначально я его оставил, как напоминание для самого себя, что это универсальная модалка

2024-12-26 14:59 UTC, Greenteyn commented on index.html
> +    <a href="/">Главная</a> -
Этот код вообще не часть проекта финального, а просто разводящая для сверстаных страничек. Но пока он есть, обернул в <nav>

2024-12-26 15:05 UTC, Greenteyn commented on src/modules/ProfileUserDataAvatarEditPopup/index.html
> +    <label class="">Выберите файл на компьютере<input type="file" accept=".jpg, .png"></label>
В форме редактирования пароля я совсем забыл поменять имена, скопировав другую форму

2024-12-26 17:51 UTC, Greenteyn commented on README.md
> +[Сайт на Netlify](https://greenteyn-messenger.netlify.app)
Чтож, кажется, самодельный роутер у меня не особо работает, поэтому, сделал пока через редиректы сервера. По крайней мере, основные ссылки все работают

2024-12-26 19:28 UTC, aromanovnik approved these changes
Поздравляю! Ваша работа принята. Все недочеты исправлены. Желаю успехов в дальнейшей учебе!

2024-12-29 16:38 UTC, merged